Update config.yaml

diff --git a/.circleci/config.yaml b/.circleci/config.yaml
--- a/.circleci/config.yaml
+++ b/.circleci/config.yaml
@@ -25,15 +25,27 @@ jobs:
       - run:
           name: Run the Docker container
           command: docker run -d -p 3000:3000 --name email-validator-app-container email-validator-app
+
       - run:
-          name: Wait for server to start
+          name: Test if server is reachable
           command: |
             for i in `seq 1 20`; do
-              nc -z localhost 3000 && echo "Server is up!" && exit 0
-              echo "Waiting for server..."
+              curl -f http://localhost:3000/validate-email -d '{"email":"test@example.com"}' && echo "Server is up!" && exit 0
+              echo "Waiting for server response..."
               sleep 1
             done
-            echo "Server failed to start in time" && exit 1
+            echo "Server failed to respond in time" && exit 1
+
+          
+      # - run:
+      #     name: Wait for server to start
+      #     command: |
+      #       for i in `seq 1 20`; do
+      #         nc -z localhost 3000 && echo "Server is up!" && exit 0
+      #         echo "Waiting for server..."
+      #         sleep 1
+      #       done
+      #       echo "Server failed to start in time" && exit 1
       - run:
           name: Run tests
           command: npm test
